// Library entry point — re-exports all public IR types.
// Consumers: import { CollectionIR } from "bruno-collection-generator";

export type {
  CollectionIR,
  CollectionInfo,
  Server,
  ServerVariable,
  Tag,
  EndpointIR,
  HttpMethod,
  ParameterIR,
  ParameterLocation,
  SchemaIR,
  SchemaType,
  DiscriminatorObject,
  ResponseIR,
  MediaTypeIR,
  HeaderIR,
  ExampleObject,
  LinkObject,
  EncodingObject,
  RequestBodyIR,
  SecurityScheme,
  HttpSecurityScheme,
  ApiKeySecurityScheme,
  OAuth2SecurityScheme,
  OAuth2Flows,
  OAuth2Flow,
  OAuth2ImplicitFlow,
  OpenIdConnectSecurityScheme,
  SecurityRequirement,
  GraphQLEndpointExtension,
  GraphQlArgumentIR,
  ValidationError,
  ValidationResult,
  Warning,
  WarningSeverity,
} from "./ir/index.js";
